### ISSUE TITLE
Fatiando installation

### ISSUE THREAD

**Issue by yassinebenhadj** [fatiando/community#45] opened 2022-01-06 13:28 UTC
I want to install fatiando, but i did not know what python i have to install (2 or 3). Can any one advise me.

**Comment by leouieda** [comment] 2022-01-06 16:07
Hi @yassinebenhadj thanks for reaching out! Depends on what you want to install:

* The `fatiando` package requires Python 2.7. It's a bit tricky to setup correctly. Check on our Slack channel for a pinned message with a full set of instructions. If you can't find it, please ask on the Slack (see https://www.fatiando.org/contact/).
* For Pooch, Harmonica, Verde, Boule, etc you'll need Python 3.6 or newer. Each package has detailed install instructions in their documentation.

Let me know if this answers your question and feel free to close this issue if it does 🙂

**Comment by yassinebenhadj** [comment] 2022-01-06 17:33
Because i am new in python, i want to understand the fatiando tools and practice the various code samples.
To install fatiando package, can i use python 3  or i must necessary use python 2.
To install python using Anaconda, i foud only the last version : Python 3.9 ( I don't found Anoconda for python 2.7)
How to download fatiando (the best way).

- I hope that you understand me .

**Comment by leouieda** [comment] 2022-01-07 10:03
>  To install fatiando package, can i use python 3 or i must necessary use python 2.

For the [`fatiando`](https://github.com/fatiando/fatiando) package it's **necessary** to use Python 2.7. The documentation for that is here: https://legacy.fatiando.org/ (note that we stopped developing this library and won't be adding or fixing things there)

For the packages we are currently developing (Harmonica, Boule, etc) it's **necessary** to use Python >= 3.6. You can get an idea of how these packages work from this tutorial: https://github.com/fatiando/tutorials

>  To install python using Anaconda, i foud only the last version : Python 3.9 ( I don't found Anoconda for python 2.7)

Since Python 2.7 reached its end of life in 2020, most people stopped distributing installers for it. You can use the Python 3.9 version and then setup a separate virtual environment with Python 2.7. I sent you a message on Slack with instructions for doing that.

**Comment by yassinebenhadj** [comment] 2022-01-07 22:54
According to your message on Slack. In order to install fatiando, i go through the following steps :
1/ Download fatiando from Github
2/ Download Anaconda (for python distribution 3.9) and install it following the instructions in  ( https://carpentries.github.io/workshop-template/#python).
3/ Create a new environment called fatiando-legacy by running the command:
     conda create --name fatiando-legacy -c conda-forge python=2.7 numpy=1.13 scipy matplotlib pillow future numba pytest
4/ Activate the fatiando-legacy environment by running the command:
    conda activate fatiando-legacy
5/ Install fatiando on that environment by running the command:
    conda install -c conda-forge fatiando

**Comment by leouieda** [comment] 2022-01-10 11:32
Yes but you can skip the first step.

**Comment by yassinebenhadj** [comment] 2022-01-10 17:59
If we skip the first step , where does conda find fatiando to install it ?

Another problem : My friend use directly python 2.7(older version of Anaconda 2 from the archive) to install fatiando, but on Anaconda prompt, solving environment does not finishes for more than 2 hours as shown below, which forced him to close it.

(base) C:\Users\HP>conda install fatiando --channel conda-forge
WARNING: The conda.compat module is deprecated and will be removed in a future release.
Collecting package metadata: done
Solving environment: \ _

**Comment by leouieda** [comment] 2022-01-11 12:13
> If we skip the first step , where does conda find fatiando to install it ?

`conda install -c conda-forge fatiando` is what fetches the package from the conda-forge repository.

> My friend use directly python 2.7(older version of Anaconda 2 from the archive) to install fatiando 

That was probably a year or two ago. They no longer distribute the Python 2.7 version since around 2020.

> solving environment does not finishes for more than 2 hours as shown below, which forced him to close it.

I'll see if I can reproduce the error here to test it out. I'll let you know if I can find a solution.

**Comment by santisoler** [comment] 2022-01-15 13:11
Hi @yassinebenhadj! Yesterday I've added **updated** instructions on how to install the old `fatiando` package with current Anaconda in the Install pages of our website: [www.fatiando.org/install](https://www.fatiando.org/install#installing-the-legacy-fatiando-package)

I've tried them yesterday on my own computer and work like charm, so feel free to try them and let us know if they work for you.

**Comment by yassinebenhadj** [comment] 2022-01-16 17:19
> Hi @yassinebenhadj! Yesterday I've added **updated** instructions on how to install the old `fatiando` package with current Anaconda in the Install pages of our website: [www.fatiando.org/install](https://www.fatiando.org/install#installing-the-legacy-fatiando-package)
> 
> I've tried them yesterday on my own computer and work like charm, so feel free to try them and let us know if they work for you.

Hi, for Anaconda installation , do i check the box (Add anaconda to my PATH environment variable) or No.

**Comment by santisoler** [comment] 2022-01-17 18:05
> Hi, for Anaconda installation , do i check the box (Add anaconda to my PATH environment variable) or No.

I would recommend going for Yes. By doing so, you will be able to run `conda` every time you open your terminal. Also the `base` environment will be activated so you'll be running the Python provided by Anaconda (instead of another Python version you might have installed -if you are running a Linux distribution, it's very likely you already have a Python version installed-).

If for any reason you don't want to use the Python provided by anaconda you can always type `conda deactivate` being in the `base` environment.

**Comment by yassinebenhadj** [comment] 2022-01-17 21:44
> > Hi, for Anaconda installation , do i check the box (Add anaconda to my PATH environment variable) or No.
> 
> I would recommend going for Yes. By doing so, you will be able to run `conda` every time you open your terminal. Also the `base` environment will be activated so you'll be running the Python provided by Anaconda (instead of another Python version you might have installed -if you are running a Linux distribution, it's very likely you already have a Python version installed-).
> 
> If for any reason you don't want to use the Python provided by anaconda you can always type `conda deactivate` while being in the `base` environment.

I have a Windows system 64 bits, and i already have Python 3.7 version installed only (without Anaconda). Now i want to install anaconda but i do not know if i have to uninstall Python 3.7 version or install directly Anaconda. That's why i asked the previous question on : check the box (Add anaconda to my PATH environment variable) or No.

**Comment by leouieda** [comment] 2022-01-21 15:22
@yassinebenhadj that depends on your preferences. Adding to the PATH means that whenever you open a terminal/cmd.exe, the Python you'll get is the Anaconda Python. If you don't use your current Python install from the terminal, then it should be OK to add Anaconda to the PATH. Otherwise, you'd have to only use Anaconda from their GUI interface (to launch Jupyter for example).

**Comment by yassinebenhadj** [comment] 2022-01-28 11:16
Hi
I followed the steps mentioned above, but i have an error 
(fatiando-legacy) C:\Users\HP>python -c "import fatiando; fatiando.test()"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named fatiando

**Comment by yassinebenhadj** [comment] 2022-01-28 11:25
Hi, during the step of activate fatiando-legacy, i have the following messages:
![image](https://user-images.githubusercontent.com/82449173/151538905-60a4cb3f-e8c6-4ad4-b2fa-441e1fe9baeb.png)

**Comment by leouieda** [comment] 2022-01-28 11:48
Hi @yassinebenhadj, let's keep the discussion in the Slack to avoid repetition. Hopefully we can get this sorted out for you 🙂

**Closed by leouieda** 2022-01-28 11:48 UTC

**Comment by yassinebenhadj** [comment] 2022-01-29 15:45
Hi, I wrote you a message in the Slack, and i am waiting for your answer.
If you didn't receive my message, tell me.
Thanks for your understanding.
